### ISSUE TITLE
Please be aware that your account is STOLEN or ABUSED by the very platform!

### ISSUE THREAD

**Issue by jbluv** [a7650/vue3-draggable-resizable#10]
Hi guys, since we're the users of the very platform.

I noticed that the platform admin stole and abused your account to make profit. Please check the two strange repo that "you" starred:

![491610674969_ pic_hd](https://user-images.githubusercontent.com/76879803/104670072-22d1bd80-5716-11eb-92a1-1c016714598b.jpg)

**Comment by MOGUIJOE** [comment]
I think GitStar.com.cn is stealing Personal Access Token from us!

**Comment by a7650** [comment]
I have logged in on other devices. 

I have fixed the problem.
