### ISSUE TITLE
any cdn import link available?

### ISSUE THREAD

**Issue by jimmychen0123** [a7650/vue3-draggable-resizable#16]
Is it possible to provide html output for can import?

**Comment by a7650** [comment]
> Is it possible to provide html output for can import?

This is an example：

<meta charset="utf-8" />
<title>Vue3DraggableResizable demo</title>
<script src="https://cdn.bootcdn.net/ajax/libs/vue/3.0.2/vue.global.js"></script>
<script src="./Vue3DraggableResizable.umd.js"></script>

<link rel="stylesheet" href="./Vue3DraggableResizable.css" />

<div id="app">
  <div class="parent">
    <draggable-resizable @drag-end="handle($event, 'id', 'drag-end')">
      This is a test example
    </draggable-resizable>
  </div>
</div>

<script>
  const DraggableResizable = Vue3DraggableResizable.default
  const DraggableContainer = Vue3DraggableResizable.DraggableContainer
  Vue.createApp({
    components: { draggableResizable: DraggableResizable },
    data() {
      return {}
    },
    mounted() {},
    methods: {
      dragEndHandle(e, id) {
        console.log(e, id)
      },
      handle(e, id, type) {
        if (type === 'drag-end') {
          this.dragEndHandle(e, id)
        }
      }
    }
  }).mount('#app')
</script>

**Comment by yangbinlovegis** [comment]
when we local develop code , we use npm to install the package; we publish the project online privately  ,we use cdn;
why I use npm install this package ,I can use `import Vue3DraggableResizable from 'vue3-draggable-resizable'` this code import this package; when I use cdn I we must use `const DraggableResizable = Vue3DraggableResizable.default` ?? . how should I use the component at the same way when import the package use different way(cdn and local).
