### ISSUE TITLE
警告setup() return property "$setWidth" should not start with "$" or "_"

### ISSUE THREAD

**Issue by cat-in-corner** [a7650/vue3-draggable-resizable#19]
示例demo
警告信息。

**Comment by chi-xy** [comment]
adsorbCols和 adsorbRows设置的时候也出现这个提示，另外，adsorbCols和 adsorbRows能动态设置吗？目前动态设置无效。

**Comment by cat-in-corner** [comment]
找到插件的包，node_modules/vue3-draggable-resizable/src/components/hooks.js
里面吧$替换成其他字符就可以了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a7650/vue3-draggable-resizable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月21日(星期三) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a7650/vue3-draggable-resizable] 警告setup() return property "$setWidth" should not start with "$" or "_" (#19)





 
adsorbCols和 adsorbRows设置的时候也出现这个提示，另外，adsorbCols和 adsorbRows能动态设置吗？目前动态设置无效。

**Comment by chi-xy** [comment]
解决了，O(∩_∩)O谢谢，送你小花花~

**Comment by cat-in-corner** [comment]
这插件好多地方都没有考虑全，自定义要花点功夫，你会发现角标拖拽不是预期的那样，还是那个hooks文件，git上问题我提问了的也有修改后的代码。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月21日(星期三) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a7650/vue3-draggable-resizable] 警告setup() return property &quot;$setWidth&quot; should not start with &quot;$&quot; or &quot;_&quot; (#19)
