### ISSUE TITLE
是否可以增加监听手柄的事件

### ISSUE THREAD

**Issue by Sai0514** [a7650/vue3-draggable-resizable#22]
您好，遇到了这样的一个需求，烦请指导~~
1. 拖动四个拐角的手柄，改变宽高比例。
2. 拖动上下轴线上的手柄，只改变高度。
3. 拖动左右轴线上的手柄，只改变宽度。
初步思路是：想通过监听控制手柄的事件，改变lockAspectRatio，但目前好像无法监测到resizing时用得哪个手柄？

**Comment by a7650** [comment]
> 您好，遇到了这样的一个需求，烦请指导~~
> 
> 1. 拖动四个拐角的手柄，改变宽高比例。
> 2. 拖动上下轴线上的手柄，只改变高度。
> 3. 拖动左右轴线上的手柄，只改变宽度。
>    初步思路是：想通过监听控制手柄的事件，改变lockAspectRatio，但目前好像无法监测到resizing时用得哪个手柄？

你好，这点确实是我设计时没考虑到的，不过你可以直接读取组件实例的resizingHandle属性，该属性是当前正在使用的手柄类型。你获取到的类型都是缩写，如：`tl`表示`top-left`，即上左方，其他的同理，我想这个应该能解决你的需求。

**Comment by Sai0514** [comment]
> > 您好，遇到了这样的一个需求，烦请指导~~
> > 
> > 1. 拖动四个拐角的手柄，改变宽高比例。
> > 2. 拖动上下轴线上的手柄，只改变高度。
> > 3. 拖动左右轴线上的手柄，只改变宽度。
> >    初步思路是：想通过监听控制手柄的事件，改变lockAspectRatio，但目前好像无法监测到resizing时用得哪个手柄？
> 
> 你好，这点确实是我设计时没考虑到的，不过你可以直接读取组件实例的resizingHandle属性，该属性是当前正在使用的手柄类型。你获取到的类型都是缩写，如：`tl`表示`top-left`，即上左方，其他的同理，我想这个应该能解决你的需求。

谢谢你的建议，问题已解决，非常感谢！
