### ISSUE TITLE
Vue3.2版本引入vue3-draggable-resizable组件出现大量警告。

### ISSUE THREAD

**Issue by 15289350313** [a7650/vue3-draggable-resizable#27]
1、[Vue warn]: injection "identity" not found.
2、[Vue warn]: setup() return property "$setWidth" should not start with "$" or "_" which are reserved prefixes for Vue internals
3、[Vue warn]: setup() return property "$setHeight" should not start with "$" or "_" which are reserved prefixes for Vue internals.

**Comment by sanoj2308** [comment]
1. [Vue warn]: setup() return property "$setWidth" should not start with "$" or "_" which are reserved prefixes for Vue internals.
2. [Vue warn]: setup() return property "$setHeight" should not start with "$" or "_" which are reserved prefixes for Vue internals. 
3. [Vue warn]: setup() return property "$setTop" should not start with "$" or "_" which are reserved prefixes for Vue internals. 
4. [Vue warn]: setup() return property "$setLeft" should not start with "$" or "_" which are reserved prefixes for Vue internals.
5. [Vue warn]: setup() return property "$setScale" should not start with "$" or "_" which are reserved prefixes for Vue internals.

 Seems like we need to remove the variable that starts with "$".

**Comment by a7650** [comment]
你好，这个是Vue内部对$和_开头的变量做的检测，其实不影响功能，我会在以后针对这个做一些修复，感谢反馈。
