### ISSUE TITLE
是否支持只允许拖拽某个指定区域？

### ISSUE THREAD

**Issue by rxliuli** [a7650/vue3-draggable-resizable#28]
如图所示
![image](https://user-images.githubusercontent.com/24560368/131807309-8a0998b8-6765-4016-b0fa-b0d21ba7883f.png)

**Comment by a7650** [comment]
> 如图所示
> ![image](https://user-images.githubusercontent.com/24560368/131807309-8a0998b8-6765-4016-b0fa-b0d21ba7883f.png)

你好，这个是支持的，可以将组件限制在其父元素的区域内，设置`parent`为true就可以了，具体可查看文档。

**Comment by rxliuli** [comment]
> > 如图所示
> > ![image](https://user-images.githubusercontent.com/24560368/131807309-8a0998b8-6765-4016-b0fa-b0d21ba7883f.png)
> 
> 你好，这个是支持的，可以将组件限制在其父元素的区域内，设置 `parent` 为 true 就可以了，具体可查看文档。

吾辈看了文档，这个属性似乎只是限制组件的拖拽范围，并没有使用它限制组件本身拖拽范围的示例
