### ISSUE TITLE
vue3引入后报错

### ISSUE THREAD

**Issue by lishihong** [a7650/vue3-draggable-resizable#3]
![image](https://user-images.githubusercontent.com/11676609/100327199-edf29580-3005-11eb-9a61-2aa1325d1ffd.png)

**Comment by a7650** [comment]
@lishihong 你好 我在最新版的1.5.3里修复了这个问题，你可以更新到1.5.3这个版本再试一下，如果还有问题可以再和我说

**Comment by lishihong** [comment]
大佬好，更新到1.5.3了，还是报这个错，是不是修复忘记合并了~

**Comment by a7650** [comment]
> 大佬好，更新到1.5.3了，还是报这个错，是不是修复忘记合并了~

你把你使用时的代码我看下

**Comment by lishihong** [comment]
![image](https://user-images.githubusercontent.com/11676609/100427066-d92d0500-30cc-11eb-8600-6d3cfdff5917.png)
这样

**Comment by lishihong** [comment]
![image](https://user-images.githubusercontent.com/11676609/100427114-eb0ea800-30cc-11eb-991e-4d39fbd009ba.png)
这样

**Comment by lishihong** [comment]
![image](https://user-images.githubusercontent.com/11676609/100427886-18a82100-30ce-11eb-9fb8-025aa0e64137.png)

**Comment by a7650** [comment]
@lishihong 你好，看样子你用的是readme里面的demo，我试了下没有问题，你用的是哪个浏览器？

**Comment by lishihong** [comment]
> @lishihong 你好，看样子你用的是readme里面的demo，我试了下没有问题，你用的是哪个浏览器？

用的chrome （版本 81.0.4044.138（正式版本） （64 位）），是的，是readme里面的demo

**Comment by sth1193101613** [comment]
> @lishihong你好，看样子你用的是readme里面的demo，我试了下没有问题，你用的是哪个浏览器？

**Comment by sth1193101613** [comment]
同样有这个报错,版本是1.5.3的

**Comment by a7650** [comment]
> 同样有这个报错,版本是1.5.3的

要不换个浏览器试试，我换了几个浏览器，无法复现这个错误，目前我不知道为什么会有这个错误。

**Comment by sth1193101613** [comment]
> > 同样有这个报错，版本是1.5.3的
> 
> 要不换个浏览器试试，我换了几个浏览器，无法复现这个错误，目前我不知道为什么会有这个错误。

handle报错信息好像是这里的

**Comment by sth1193101613** [comment]
作者看到麻烦加下我qq 1193101613

**Comment by sth1193101613** [comment]
作者看到麻烦加下我微信 s1193101613
