### ISSUE TITLE
[Question] How can I get Parent Width and Parent Height

### ISSUE THREAD

**Issue by zhangj1an** [a7650/vue3-draggable-resizable#34]
In `VueDraggableResizable` component, the function `setup()` will return a parameter `...parentSize` that contains `parentWidth` and `parentHeight`. How can I access this two parameters?

I tried adding `ref="root"` into the `<Vue3DraggableResizable/>` and access using `root.parentWidth`, but was unccessful. 

Thanks in advance!

**Comment by zhangj1an** [comment]
My actual problem is, after dragging, I want the item's position to be relative to its parent component in units of %, rather than an absolute position of px. 

How can I achieve this? 
Sorry for posting issues so often. Thanks in advance :D

**Comment by a7650** [comment]
> 

Maybe you can access the properties of this component instance directly.
