### ISSUE TITLE
1.6.1 版本

### ISSUE THREAD

**Issue by fxt-coder** [a7650/vue3-draggable-resizable#37]
最新版本，项目跑起来  
These relative modules were not found:

* ./components/DraggableContainer in ./node_modules/vue3-draggable-resizable/src/index.js
* ./components/Vue3DraggableResizable in ./node_modules/vue3-draggable-resizable/src/index.js
components里面的js文件跟上个版本比较都没有了

**Comment by bleachc** [comment]
There's a closed issue where someone resolved this by adding TypeScript

https://github.com/a7650/vue3-draggable-resizable/issues/33

We're using 1.5.4 without TypeScript and it's working.
