### ISSUE TITLE
error

### ISSUE THREAD

**Issue by streakSnail** [a7650/vue3-draggable-resizable#39]
* ./components/DraggableContainer in ./node_modules/_vue3-draggable-resizable@1.6.1@vue3-draggable-resizable/src/index.js
* ./components/Vue3DraggableResizable in ./node_modules/_vue3-draggable-resizable@1.6.1@vue3-draggable-resizable/src/index.js

**Comment by xiaolong-xl** [comment]
这个错误 作者快点解决下，看了源码 这个错误报的有点离谱

**Comment by a7650** [comment]
> * ./components/DraggableContainer in ./node_modules/_vue3-draggable-resizable@1.6.1@vue3-draggable-resizable/src/index.js
> * ./components/Vue3DraggableResizable in ./node_modules/_vue3-draggable-resizable@1.6.1@vue3-draggable-resizable/src/index.js

你怎么引用的代码贴出来看下

**Comment by a7650** [comment]
> 这个错误 作者快点解决下，看了源码 这个错误报的有点离谱

确实有点离谱，别人都没有，可能是环境问题

**Comment by xiaolong-xl** [comment]
> import Vue3DraggableResizablea from 'vue3-draggable-resizable'
import 'vue3-draggable-resizable/dist/Vue3DraggableResizable.css'

createApp(App)
  .use(ElementPlus, {
    locale: zhCn
  })
  .use(Vue3DraggableResizablea)
  .use(components)
  .use(store)
  .use(utils)
  .use(filters)
  .use(router)
  .mount('#app');

**Comment by xiaolong-xl** [comment]
> > 这个错误作者快点解决下，分析源码一个错误报告的有点离谱
> 
> 确实离谱，别人都没有，可能是环境问题

环境 也就是用的vue3 脚手架搭建出来的  执行了src/index 文件 但是 Index文件里面 require("./components/Vue3DraggableResizable");和 require("./components/DraggableContainer");的找不到 
我想提问的一点：如果访问index.js里面 使用了"use strict"（严格模式）;引入ts文件是可行？

**Comment by LibinLin** [comment]
同出现了这个问题，请问要怎么解决

**Comment by X3587** [comment]
大佬解决了吗

**Comment by a7650** [comment]
哪位有问题，搞个demo的工程，我试下。
