### ISSUE TITLE
Auto sizing feature ?

### ISSUE THREAD

**Issue by colxi** [a7650/vue3-draggable-resizable#4]
Hi there, I've been playing a bit with your library and I've found it very smartly designed and versatile, but I'm missing a feature that I am not sure if is available.

Is there any way to enable automatic sizing for width and height, according to the inner contents?

I'm dynamically showing and hiding some parts of the contents injected inside the `Vue3DraggableResizable`  component, and I would need the container to react to the new area, but I found no way so far.
Is such a feature covered by the library?

**Comment by a7650** [comment]
Thank you for your advice, I think adding this feature may cause other problems, but I have an idea.
You can get the width manually after the visibility of the content has changed, then use `v-model:w="w"` to change the component props.
I don't know if this can meet your requirements. If not, plz feel free to communicate with me again.

**Comment by a7650** [comment]
> Hi there, I've been playing a bit with your library and I've found it very smartly designed and versatile, but I'm missing a feature that I am not sure if is available.
> 
> Is there any way to enable automatic sizing for width and height, according to the inner contents?
> 
> I'm dynamically showing and hiding some parts of the contents injected inside the `Vue3DraggableResizable` component, and I would need the container to react to the new area, but I found no way so far.
> Is such a feature covered by the library?

Thank you for your advice, I think adding this feature may cause other problems, but I have an idea.
You can get the width manually after the visibility of the content has changed, then use v-model:w="w" to change the component props.
I don't know if this can meet your requirements. If not, plz feel free to communicate with me again.
