### ISSUE TITLE
左下和右上点缩放基准点位置错误

### ISSUE THREAD

**Issue by Juaoie** [a7650/vue3-draggable-resizable#43]
左上角和右下角缩放没问题，左下角和右上角缩放基准点不正确，左下角缩放基准点在右下角，右上角缩放基准点在左上角了

**Comment by Juaoie** [comment]
解决如下：
![图片](https://user-images.githubusercontent.com/34809384/146729357-6cc91b83-3581-4266-98d0-dd90e62d2718.png)

**Comment by Seraphli** [comment]
同样发现有问题

**Comment by wangs1991** [comment]
提交了修改该问题的 Pull request，需要的可以看下 [#51 ](https://github.com/a7650/vue3-draggable-resizable/pull/51)

**Comment by a7650** [comment]
确实有问题，修复过了
