### ISSUE TITLE
引入错误

### ISSUE THREAD

**Issue by libinLee** [a7650/vue3-draggable-resizable#45]
在单个页面引入：
import Vue3DraggableResizable  from 'vue3-draggable-resizable'
import 'vue3-draggable-resizable/dist/Vue3DraggableResizable.css'

报错：
These relative modules were not found:
./components/DraggableContainer in ./node_modules/vue3-draggable-resizable/src/index.js
./components/Vue3DraggableResizable in ./node_modules/vue3-draggable-resizable/src/index.js

**Comment by Shawn8585** [comment]
请问下解决了吗
