### ISSUE TITLE
[Vue warn]: injection "identity" not found. 

### ISSUE THREAD

**Issue by eyun-tv** [a7650/vue3-draggable-resizable#46]
发现一个警告
[Vue warn]: injection "identity" not found. 
  at <Vue3DraggableResizable key=0 draggable=true initH=546  ... > 
  at <Area> 
  at <Index>

**Comment by a7650** [comment]
这个不影响，因为部分功能要配合`DraggableContainer`使用，所以使用了inject。
如果单独使用`Vue3DraggableResizable`的话就会报这个warn，忽略即可。

**Comment by Danny-Yxzl** [comment]
> 这个不影响，因为部分功能要配合`DraggableContainer`使用，所以使用了inject。 如果单独使用`Vue3DraggableResizable`的话就会报这个warn，忽略即可。

但是这样的warning很烦人……有什么解决方案吗？
