### ISSUE TITLE
Support touch device

### ISSUE THREAD

**Issue by nguyenhongphat0** [a7650/vue3-draggable-resizable#5]
Hello there, thank you for the great work!
I'm currently using this library in my Vue 3 project, it works fine on desktop device with mouse/touchpad, but it would be better if the draggable/resizable support touch device!

**Comment by nguyenhongphat0** [comment]
Hope these resource might help: https://www.w3schools.com/jsref/event_touchstart.asp, https://www.w3schools.com/jsref/event_touchstart.asp

**Comment by a7650** [comment]
> Hello there, thank you for the great work!
> I'm currently using this library in my Vue 3 project, it works fine on desktop device with mouse/touchpad, but it would be better if the draggable/resizable support touch device!

Thanks for your suggestion, I think it's great and I will add this feature in the next few days.

**Comment by a7650** [comment]
> Hello there, thank you for the great work!
> I'm currently using this library in my Vue 3 project, it works fine on desktop device with mouse/touchpad, but it would be better if the draggable/resizable support touch device!

Hi，I just released a beta version of 1.6.0，you can install it with the command  `npm install vue3-draggable-resizable@beta`.

**Comment by nguyenhongphat0** [comment]
Wow so quick, thank you so much :1st_place_medal:
