### ISSUE TITLE
嵌套问题

### ISSUE THREAD

**Issue by CeruleanLee** [a7650/vue3-draggable-resizable#52]
请问：当vue3-draggable-resizable 中继续嵌套一个vue3-draggable-resizable时， 内层拖动会影响外层一起动，有什么解决方案吗？
万分感谢！

**Comment by a7650** [comment]
> 请问：当vue3-draggable-resizable 中继续嵌套一个vue3-draggable-resizable时， 内层拖动会影响外层一起动，有什么解决方案吗？ 万分感谢！

`@mousedown.stop=""`   ，在Vue3DraggableResizable组件上加一个这个阻止冒泡就行了
