### ISSUE TITLE
使用对齐线错误，请问是什么问题呢！

### ISSUE THREAD

**Issue by timosss** [a7650/vue3-draggable-resizable#56]
拖动一个组件 所有的Vue3DraggableResizable跟着一起动！
![微信截图_20220520000954](https://user-images.githubusercontent.com/27383568/169347520-1f37dd56-9d07-4f20-9860-46a14fe9493b.png)

<DraggableContainer>
      <Vue3DraggableResizable>
        Test
      </Vue3DraggableResizable>
      <Vue3DraggableResizable>
        Test
      </Vue3DraggableResizable>
    </DraggableContainer>

**Comment by a7650** [comment]
> 

你好，能否提供一个复现的demo让我看下
