### ISSUE TITLE
组件激活状态变为非活跃状态

### ISSUE THREAD

**Issue by DYJ1427** [a7650/vue3-draggable-resizable#58]
你好，在Vue3DraggableResizable里，active跟它的绑定值并没有关系啊，只要是点击这个组件外的位置都会变成非活跃状态，我要在旁边编辑修改点击组件的属性，需要保持活跃状态，请问能尽快修复一下这个问题吗，谢谢

**Comment by a7650** [comment]
你好，目前默认是点击组件以外的区域会取消掉active状态的，这个active是双向的，就是组件内部会修改这个值，同时你在组件外部也可以修改这个值，并不是说你在外部把这个置为true，这个组件就一直是active的状态了。

对于你这个问题，有个解决办法，就是你在你的编辑面板上监听`mousedown`事件并加一个`.stop`修饰符，因为取消active这个行为是监听document上的mousedown事件的，你加了.stop修饰符之后，这个事件就不会传递到document上了，也就不会取消active状态了。

注意如果你在移动端使用这个组件，你需要把`mousedown`换成添加`touchstart`。

**Comment by DYJ1427** [comment]
> 

好的 谢谢大佬
