### ISSUE TITLE
parent 宽度动态变化

### ISSUE THREAD

**Issue by gogowj123** [a7650/vue3-draggable-resizable#59]
当父组件的宽度动态变化的时候，如果设置:parent="true"，那么组件扩大缩小时只能扩大到父组件初始的宽度，有什么办法吗

**Comment by a7650** [comment]
拖拽组件实例上有个parentWidth属性，你可以尝试在父组件宽度变化后修改这个属性试试。

如果不行的话，你可以再联系我。
