### ISSUE TITLE
warnings for props starting with "$"

### ISSUE THREAD

**Issue by gabrielegiammatteo** [a7650/vue3-draggable-resizable#6]
When I create a new Vue3DraggableResizable component as described in the README
```
    <Vue3DraggableResizable
      :initW="110"
      :initH="120"
      v-model:x="x"
      v-model:y="y"
      v-model:w="w"
      v-model:h="h"
      v-model:active="active"
      :draggable="true"
      :resizable="true"
      @activated="print('activated')"
      @deactivated="print('deactivated')"
      @drag-start="print('drag-start')"
      @resize-start="print('resize-start')"
      @dragging="print('dragging')"
      @resizing="print('resizing')"
      @drag-end="print('drag-end')"
      @resize-end="print('resize-end')"
    >
```
I get multiple warnings:

![Screenshot_2021-01-04_18-01-14](https://user-images.githubusercontent.com/4500049/103560048-6a0ab380-4eb7-11eb-9190-4014e1e05f28.png)

The first one has been already addressed in #2, but for the other ones I think there is no fix yet

This is my package.json:

![Screenshot_2021-01-04_18-01-56](https://user-images.githubusercontent.com/4500049/103560087-78f16600-4eb7-11eb-8907-1e42ba057f5b.png)

**Comment by a7650** [comment]
@gabrielegiammatteo 
Thank you for your question, this warning is because I used a variable that starts with "$", but it does not affect normal use, I will remove this warning in the next release.
