### ISSUE TITLE
建议 拖放前重新获取一下父元素宽高

### ISSUE THREAD

**Issue by 4566704** [a7650/vue3-draggable-resizable#64]
parent 属性为 true时，当 parent 大小发生改变时，移动限制并没有变化，因为在元素初始化时获取的parent。
建议 拖放前重新获取一下父元素宽高。我看不懂源码，改了好几处地方都没生效

**Comment by a7650** [comment]
好的，这点确实应该重新获取下，我近期改一下，感谢建议。

**Comment by zhumj** [comment]
快一年了还没加上这功能

**Comment by 4566704** [comment]
个人开源的项目是这样的，好多地方要改

**Comment by zhumj** [comment]
你改好了么？需要怎么改？新手表示看不懂源码
