### ISSUE TITLE
【vite】npm run build not could not load index.css 

### ISSUE THREAD

**Issue by huhansheng** [a7650/vue3-draggable-resizable#75]
npm run build happen error.
<img width="440" alt="5ee03482778e4230af1aaf9f5b2f874a" src="https://user-images.githubusercontent.com/19321222/186304568-7c852792-754b-4292-b016-5c0d5279af26.png">

I look find 'node_modules/vue3-draggable-resizable/src/components/index.css ' is exist. so i think version‘error，but i remove and npm install vue3-draggable-resizable，that error also。

why？

**Comment by a7650** [comment]
Maybe you don't have the corresponding loader?
