### ISSUE TITLE
Unable to move objects around on mobile

### ISSUE THREAD

**Issue by spaceemotion** [a7650/vue3-draggable-resizable#8]
We've previously used https://github.com/mauricius/vue-draggable-resizable and recently tried to update to vue 3, but this one bug is preventing the upgrade.

While the touch events are registered (https://github.com/a7650/vue3-draggable-resizable/blob/main/src/components/hooks.ts#L225-L227), trying to drag a container around just scrolls the page instead (tested on both, Android and iPhone).

**Comment by a7650** [comment]
> We've previously used https://github.com/mauricius/vue-draggable-resizable and recently tried to update to vue 3, but this one bug is preventing the upgrade.
> 
> While the touch events are registered (https://github.com/a7650/vue3-draggable-resizable/blob/main/src/components/hooks.ts#L225-L227), trying to drag a container around just scrolls the page instead (tested on both, Android and iPhone).

I'm sorry to have caused you such confusion. This feature is currently only available in the beta version,  you need to install the beta version.

You can install it with the command **`npm install vue3-draggable-resizable@beta`**.

Please feel free to communicate with me if you have any problems.
