### ISSUE TITLE
Support Rotatable

### ISSUE THREAD

**Issue by nguyenhongphat0** [a7650/vue3-draggable-resizable#9]
Hello team, you are doing amazing!

I know this library is focus on draggable + resizable, but since there is no rotatable lib that support Vue 3 yet, it would be great if this lib can. You can provide a new prop, like :rotatable="true", or create a new library that extends from this library. Please consider this!

![image](https://user-images.githubusercontent.com/29925961/104403165-80390380-558a-11eb-961c-1e6832abc248.png)

**Comment by a7650** [comment]
> Hello team, you are doing amazing!
> 
> I know this library is focus on draggable + resizable, but since there is no rotatable lib that support Vue 3 yet, it would be great if this lib can. You can provide a new prop, like :rotatable="true", or create a new library that extends from this library. Please consider this!
> 
> ![image](https://user-images.githubusercontent.com/29925961/104403165-80390380-558a-11eb-961c-1e6832abc248.png)

Thanks for your suggestion, this feature is in the plan, but I am too busy to do it recently.

**Comment by nguyenhongphat0** [comment]
Thank you for considering it 🥰

**Comment by geminigeek** [comment]
hi, any plan to add this rotate feature ?
